### PR TITLE
refactor: use the ini_file module to test sssd.conf

### PR DESCRIPTION
**Pull request by richm**
The `ini` lookup is problematic with ansible 2.9 due to the
arguments being completely different, and because ansible attempts
to evaluate `{{ lookup('ini', ...) }}` even if guarded by a `when`,
any use of the new style 2.x `ini` arguments will fail.
Instead, just use the `ini_file` module itself, and rely on the fact
that it will report `changed: true` if the values are different.

Refactor the `tests_dyndns.yml` test so that it works in CI with
a single host - in that case, just check that the sssd.conf was
written correctly.

The `tests_dyndns.yml` test wasn't working properly - in order for
any parameters to be set, you must specify `ad_dyndns_update: true`

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Comment by richm** [comment]
@jakub-vavra-cz  @justin-stephenson ptal

**Comment by richm** [comment]
[citest]

**Comment by justin-stephenson** [comment]
> Refactor the `tests_dyndns.yml` test so that it works in CI with a single host - in that case, just check that the sssd.conf was written correctly.

I'm not QE so I will defer to @jakub-vavra-cz  but I thought it would be better skip this test when AD is not available, to not give the false impression that dynamic DNS testing was successful in the case of a single host where dynamic DNS functionality is impossible.

Unrelated, one minor typo in the filename  `sed 's/tests_sssd_custom_setttings.yml/tests_sssd_custom_settings.yml/'`

Code changes LGTM.

**Comment by richm** [comment]
> > Refactor the `tests_dyndns.yml` test so that it works in CI with a single host - in that case, just check that the sssd.conf was written correctly.
> 
> I'm not QE so I will defer to @jakub-vavra-cz but I thought it would be better skip this test when AD is not available, to not give the false impression that dynamic DNS testing was successful in the case of a single host where dynamic DNS functionality is impossible.

Understood - but I really wanted to have a way to test the ini file handling stuff without having to set up a real AD.  And I did uncover an issue with the tests_dyndns.yml

If you do have a linux and an AD host in your inventory, the test will check that DNS is configured properly.

> 
> Unrelated, one minor typo in the filename `sed 's/tests_sssd_custom_setttings.yml/tests_sssd_custom_settings.yml/'`

Thanks - fixed

> 
> Code changes LGTM.

**Comment by richm** [comment]
[citest]

**Comment by justin-stephenson** [comment]
Ack from my side.

**Pull request merged**
